FROM mcr.microsoft.com/dotnet/aspnet:5.0

# RUN ["apt-get", "update"]
# RUN ["apt-get", "install", "-y", "vim"]
# RUN ["apt-get", "install", "curl", "-y"]

RUN echo "alias ll='ls -al --color'" >> ~/.bashrc

# The wildcard skips copying subdirectories, strangely enough...
COPY ./built_server_app/ app/

WORKDIR /app

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "Omega.dll"]
