version: '3.7'

x-omega-vars: &omega-vars
  AUTH_HOST: 'omega_auth'
  AUTH_PORT: '80'
  CORE_HOST: 'omega_core'
  CORE_PORT: '80'
  WEATHER_HOST: 'omega_weather'
  WEATHER_PORT: '80'
  OMEGA_DEFAULT_DB_HOST: 'omega_mssql'
  OMEGA_DEFAULT_DB_PORT: '${OMEGA_MSSQL_CONTAINER_PORT}'
  OMEGA_SEQ_HOST: 'omega_seq'
  OMEGA_SEQ_INGESTION_PORT: '${OMEGA_SEQ_INGESTION_PORT}'

services:
  omega_web:
    image: omega_web:1.0
    container_name: omega_web
    build:
      context: .
      dockerfile: Dockerfile.web
    networks:
      - omega-net
    environment:
      <<: *omega-vars
      SERVICE_KEY: 'Web'
    ports:
      - '5000:80'
      - '5001:443'
  omega_auth:
    image: omega_auth:1.0
    container_name: omega_auth
    build:
      context: .
      dockerfile: Dockerfile.service
    networks:
      - omega-net
    environment:
      <<: *omega-vars
      SERVICE_KEY: 'Auth'
    expose:
      - 80
      - 443
  omega_core:
    image: omega_core:1.0
    container_name: omega_core
    build:
      context: .
      dockerfile: Dockerfile.service
    networks:
      - omega-net
    environment:
      <<: *omega-vars
      SERVICE_KEY: 'Core'
    expose:
      - 80
      - 443
  omega_weather:
    image: omega_weather:1.0
    container_name: omega_weather
    build:
      context: .
      dockerfile: Dockerfile.service
    networks:
      - omega-net
    environment:
      <<: *omega-vars
      SERVICE_KEY: 'Weather'
    expose:
      - 80
      - 443
      
networks:
  omega-net:
    name: omega-net
    external: true
