version: "3.7"

services:
  omega_web:
    image: omega_web:1.0
    container_name: omega_web
    build:
      context: .
      dockerfile: Dockerfile.web
    networks:
      - omega
    environment:
      SERVICE_KEY: "Web"
      AUTH_HOST: "omega_auth"
      AUTH_PORT: "80"
      CORE_HOST: "omega_core"
      CORE_PORT: "80"
      WEATHER_HOST: "omega_weather"
      WEATHER_PORT: "80"
    ports:
      - "5000:80"
      - "5001:443"
  omega_auth:
    image: omega_auth:1.0
    container_name: omega_auth
    build:
      context: .
      dockerfile: Dockerfile.service
    networks:
      - omega
    environment:
      SERVICE_KEY: "Auth"
    expose:
      - 80
      - 443
  omega_core:
    image: omega_core:1.0
    container_name: omega_core
    build:
      context: .
      dockerfile: Dockerfile.service
    networks:
      - omega
    environment:
      SERVICE_KEY: "Core"
    expose:
      - 80
      - 443
  omega_weather:
    image: omega_weather:1.0
    container_name: omega_weather
    build:
      context: .
      dockerfile: Dockerfile.service
    networks:
      - omega
    environment:
      SERVICE_KEY: "Weather"
    expose:
      - 80
      - 443
      
networks:
  omega:
    name: omega
    driver: bridge
