#!/bin/bash 

# Old vanilla way
# docker build -t omega:1.0  .

# Comment out dotnet publish/yarn build for faster testing of docker changes
# TODO: new setup to do these in parllel (maybe with gulp?)
# Note: WSL ubuntu bash hangs on the dotnet command...
# echo "publishing Release version of app..."
# pushd ../
# dotnet publish -c Release
# popd
# pushd ../Omega/client-app/
# yarn build
# popd

echo "copying files to ./app..."
rm -rf ./app
mkdir ./app
cp -r ../Omega/bin/Release/net5.0/publish/. ./app/
rm -rf ./app/client-app
mkdir -p ./app/client-app/build
cp -r ../Omega/client-app/build ./app/client-app/

echo "running docker-compose build"
docker-compose build
