#!/bin/bash 

# docker build -t omega:1.0  .

# Publishing outside of this proecess for now since it's slow and we're just testing docker config
# echo "publishing Release version of app..."
# TODO: push dir
# dotnet publish -c Release
# TODO: pop dir

echo "copying files to ./app..."
rm -rf ./app
mkdir ./app
cp -r ../Omega/bin/Release/net5.0/publish/* ./app/

echo "running docker-compose build"
docker-compose build
