version: "3.8"

services:
  omega_web:
    image: omega:web
    container_name: omega_web
    build:
      context: .
      dockerfile: Dockerfile.web
    networks:
      - omega
    environment:
      IS_WEB: "true"
      TEST_VAR: "hello world"
      DOT_ENV_TEST_VAR: "localhost:5003"
      CORE_HOST: "omega_core"
      CORE_PORT: "80"
    ports:
      - "5000:80"
      - "5001:443"
  omega_core:
    image: omega:core
    container_name: omega_core
    build:
      context: .
      dockerfile: Dockerfile.services
    networks:
      - omega
    environment:
      TEST_VAR: "hello world"
      DOT_ENV_TEST_VAR: "localhost:5003"
    expose:
      - 80
      - 443
      
networks:
  omega:
    name: omega
    driver: bridge
