version: "3.8"

services:
  omega_web:
    image: omega:1.0
    container_name: omega_web
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - omega
    environment:
      TEST_VAR: "hello world"
    ports:
      - "5000:80"
      - "5001:443"
    expose:
      - 80
      - 443
      
networks:
  omega:
    name: omega
    driver: bridge
